# Порт для запуска сервера
app:
  port: "43000"

# Адрес и порт для проверки state (удаленныый клиент)
serversSync:
  srv: "127.0.0.1"
  port: "8000"

# Типы проверок 
type:
  sh: 
  tcp: 
    host: "127.0.0.1"
    port: "43000"

# Тип интерфейса который надо отключать или включать (vip)
interfaces:
  name: "eth0"
  ip: "192.168.135.137/20"